// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:houlala_app/features/carts/cart_item.dart';
import 'package:houlala_app/features/category/category_model.dart';
import 'package:houlala_app/features/locals/local_model.dart';
import 'package:houlala_app/features/product_type/product_type.dart';
import 'package:houlala_app/features/products/product.dart';
import 'package:houlala_app/features/suggestion/suggestion.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(LocalModelAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(ProductTypeAdapter());
    registerAdapter(SuggestionAdapter());
  }
}
